dist: bionic

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install: pip install poetry

install: pip install tox-travis coveralls

script:
  - tox

jobs:
  include:
    - stage: coveralls
      script:
        - coverage combine
        - coveralls
      python: "3.8"